### ISSUE TITLE
Check if required files are changed after running `npm run release`

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#10]

**Comment by maxkfranz** [comment]
E.g. check git diff for the files

**Comment by AkMo3** [comment]
- Dist
- Docs

**Comment by maxkfranz** [comment]
- index.html : https://github.com/AkMo3/cytoscape.js/blob/unstable/documentation/index.html
- docs cy.js file : https://github.com/AkMo3/cytoscape.js/blob/unstable/documentation/js/cytoscape.min.js
- dist: https://github.com/AkMo3/cytoscape.js/tree/unstable/dist

**Comment by maxkfranz** [comment]
Way to test:

Edit the source of the library: e.g. core/index.js and just add a log.  That will make the code different enough for a diff, and you verify that the files are correct that way.

**Comment by AkMo3** [comment]
List of files that should be updated are:
1. dist/cytoscape.cjs.js
2. dist/cytoscape.esm.js
3. dist/cytoscape.esm.min.js
4. dist/cytoscape.min.js
5. dist/cytoscape.umd.js
6. documentation/index.html
7. documentation/js/cytoscape.min.js
8. documentation/versions.json

Verified after making a sample release

**Comment by AkMo3** [comment]
Steps involved in performing the action:

1. Check if $VERSION is set
2. Push new $VERSION to documentation/versions.js
3. Create a set of directory/files to be check
4. For each file, check if it is modified using `git status -s $file`
5. If the file not modified exit out as a failure
