### ISSUE TITLE
Version updates in merge_unstable_to_master.sh

### ISSUE THREAD

**Issue by maxkfranz** [AkMo3/cytoscape.js#16]
https://github.com/AkMo3/cytoscape.js/blob/ebddf4769eaf019526083cdd9839ea4772b3bb90/.github/workflows/scripts/merge_unstable_to_master.sh#L58-L62

This corresponds to step (4)(ii)(e).

The point of this step is that the unstable branch should have some version number on it that's sensible:

- If someone (e.g. an external contributor) looks at the unstable branch, they should know that the branch is for new, next version features.
- The version should not match the same as the release we are about to make.

Make a release of $VERSION, then we want $VERSION+1 for unstable.

E.g. `1.2.0` is being released, then version in package.json should be `1.3.0-unstable`

**Comment by AkMo3** [comment]
Done. 
Version in unstable will be bumped by 1 and appended with `-unstable`

https://github.com/AkMo3/cytoscape.js/blob/dcac71c409aaccd942721b7189267fec99f6ec18/.github/workflows/scripts/merge_unstable_to_master.sh#L103-L109

**Comment by AkMo3** [comment]
1. Use the `temp` directory to create a temporary file. Eg: `/tmp/temp.json`
2. Find the version of `jq` being used currently, and check later on if we are using the same version later on.
