### ISSUE TITLE
Update documentation re. new release process

### ISSUE THREAD

**Issue by maxkfranz** [AkMo3/cytoscape.js#25]
Update the README with information about how the new process works:

- [x] The release process needs an access token
- [x] Note the secrets necessary

Note the steps that someone has to carry out for each type of release in the README:

- [x] Backport
- [x] Patch/bugfix
- [x] New feature release

Misc.

- [x] Update the readme and move the current manual steps into a new file under `.github` dir

**Comment by AkMo3** [comment]
Add documentation assuming they have never done a release before and doesn't know about github actions
