### ISSUE TITLE
Checkout repository and select patch branch

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#3]
Purpose:

- When a milestone is closed, this should indicate that the release should be made for that milestone.
- Closing a milestone is a trigger for the GH actions release process.

Timeline:

- Milestone gets closed
- GH actions starts
- There is some gating that blocks the GH action from finishing ('permanent' actions/results -- npm release), and someone needs to hit a button or something to confirm first

Details:

This task consists of action to checkout the appropriate branch for a patch release, which can be done using two ways:
1. Manually giving input using [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
2. On completion of a milestone, get the label of milestone which specifies the release to which the patch be applied.
3. Documentation: The trigger needs to be obvious to everyone.

Inputs:

- Branch
- Type of release that you're making: patch / feature -- apply to most/all of the scripts/actions

Testing: How do we confirm that this is working.

- Example GH action
- Test on closing of milestone in this repo -- scope this to a particular milestone name (testissue3)
- Or: disable the test gh action when done
- Manually confirm

**Comment by maxkfranz** [comment]
For future (maybe):  Mike's suggestion re. the automatic type of release (patch versus feature) => automatically inferred by the version number in future

**Comment by AkMo3** [comment]
Move from composite actions to bash scripts

**Comment by AkMo3** [comment]
Updated [patch-release-test.yml](https://github.com/AkMo3/cytoscape.js/blob/unstable/.github/workflows/patch-release-test.yml) to use bash script to get patch branch defined in [parse-branch-from-milestone.sh](https://github.com/AkMo3/cytoscape.js/blob/unstable/.github/workflows/parse-branch-from-milestone.sh).

Setting the output to environment variable with label `PATCH_BRANCH`
