### ISSUE TITLE
Create a action to automatically determine new version string for releases

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#4]
The action should correspond to the below behaviour:

- For Feature Release: 1.2.3 => 1.3.0
- For Patch Release:    1.2.3 => 1.2.4

**Comment by AkMo3** [comment]
Currently created a script to fetch an updated version for a patch release. It does it in the following way:
1. Downloads a [node script](https://github.com/AkMo3/cytoscape.js/blob/unstable/.github/workflows/scripts/Parse-Version-String.js).
2. The script parses the package.json into a JSON and obtains the version value.
3. Divides the version into 4 sections: `Major`, `Minor`, `Build`, `Rest`
4. Increment the `Build` and generate a new version by concatenating all the rest.
5. Outputs this to bash script where the bash scripts sets the environment variable `NEW_PATCH_VERSION`

**Comment by AkMo3** [comment]
Tested Github Action: https://github.com/AkMo3/cytoscape.js/actions/runs/5180870354/jobs/9335628494

**Comment by maxkfranz** [comment]
To investigate once the scripts are ready (later step): Replacement of curl.  Run the scripts directly in the GH action.

**Comment by maxkfranz** [comment]
Before closing: Let's create a new issue for curl

**Comment by AkMo3** [comment]
Issue create: #14
