### ISSUE TITLE
Write script to merge unstable to master for feature release

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#5]
As per the release instructions:
```
    1. Make sure your local master is up-to-date: git checkout master && git pull
    2. Make sure your local unstable is up-to-date: git checkout unstable && git pull
    3. Create a merge commit that selects the state of unstable and push it: git merge -s ours master && git push
    4. Fast-forward master to the merge commit: git checkout master && git merge unstable && git push
    5. Update the version number in package.json and package-lock.json on unstable to some provisional new version number, and push it.
```

This tasks also requires handling GitHub secrets to enable secure push to remote.

**Comment by maxkfranz** [comment]
- Run through the merge process manually
- Thinking about and logging in this issue: What are edge cases where things could go wrong?

**Comment by AkMo3** [comment]
Prerequisite:
1. New Version
2. Current branch
3. And figure other...

**Comment by AkMo3** [comment]
Added shell script to perform the above steps and checks in between. Integration with GitHub action is pending. 
Shell Script: [merge_unstable_to_master.sh](https://github.com/AkMo3/cytoscape.js/blob/unstable/.github/workflows/scripts/merge_unstable_to_master.sh)

**Comment by AkMo3** [comment]
Successfully ran the GitHub action to merge unstable to master. Please check [Feature Release Test #21](https://github.com/AkMo3/cytoscape.js/actions/runs/5271707270)

**Comment by AkMo3** [comment]
The script has the following features:

1. Exit on first command failure. Achieved using `set -e` option.
2. Check if `$VERSION` is set.
3. Setting configs to the `ACTOR` of the GitHub action, i.e., who initiates the action. Achieved using below code snippet
```
# Set git configs
git config --global user.name "${GITHUB_ACTOR}"
git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
```
4. Check if the branch is set to `unstable`,
5. Executes the merge process as per documentation.
6. Checks if the version has been successfully updated in `package.json` and `package-lock.json`.
