### ISSUE TITLE
Task #5: Run tests

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#6]

**Comment by maxkfranz** [comment]
- Tests are useful for blocking a release
  - Requirement: If the automated tests fail, even if the milestone is closed, no release should be made
  - Requirement: Nice if there were some notification (GH failure, already?)

**Comment by AkMo3** [comment]
Things to investigate: 
1. Should we store any artifacts related to testing?
2. Is `npm run tests` enough?

**Comment by maxkfranz** [comment]
- `npm test` without the html is sufficient
- `npm test` should have an exit you can read

**Comment by maxkfranz** [comment]
`npm test` might also include linting (exit code?)

alternative: `npm run test:js`
