### ISSUE TITLE
Task #6: Run release and update documentation

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#7]
This task includes the creation of a composite action that :

1. Prepare release
2. Update documentation

**Comment by maxkfranz** [comment]
Let's separate out these issues if possible

**Comment by AkMo3** [comment]
`sed -i "s*## Releases*## Releases\n- 3.26.0\n    - [3.26.0](https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.25.0+is%3Aclosed)*g" ./intro.md`

**Comment by maxkfranz** [comment]
Prepare release

- Running it is simple
- Verify it actually ran properly -- manually => automated

Documentation:

- Indentation is important
- Ordering of the releases is important
- There may be a missing bullet point where your new release should go
- It's manual now
- Good to outline how / planned impl
- Alt: sed
- Alt: use the html template and have the list of releases as json input

**Comment by maxkfranz** [comment]
- have some script to update the docs md / template (pref.  template)
  - list of json versions: `["1.2.3", "1.2.4", "1.3.0", ...]`
  - when making release push new entry to array (jq?)
  - update the template to read the json file
    - dockermaker.js - read the json versions, process it into a hierarchy
      - sorted hierarchy:
        - 1.3
          - 1.3.1
          - 1.3.0   
        - 1.2
          - 1.2.1
          - 1.2.0
   - template should use the the process versions hierarchy to print the md list
- `npm run release

**Comment by maxkfranz** [comment]
Approach: Add support for handlebars templates within md files

- Let's use a convention: 
  - `md` key for the markdown file
  - `mdjson` / `mdhb` key for the markdown template json input 
- Add `mdjson` for the intro section (`intro.md`) 
  - `md`: intro.md
  - `mdjson`: versions.json
- Update the docmaker.js file to run handlebars on the section md intput as a first pass (before running markdown compiler) only if the `mdjson` key is there 
- Avoid running extra hb steps on sections that don't need it

**Comment by AkMo3** [comment]
How I am achieving it currently:
1. Edited [intro.md](https://github.com/AkMo3/cytoscape.js/blob/unstable/documentation/md/intro.md) by replacing all versions with a template.

https://github.com/AkMo3/cytoscape.js/blob/e4de815b719aaf594686e6be8bf4aec46f4cd17c/documentation/md/intro.md?plain=1#L278-L297

2. Added all versions to docmaker.json in a new versions array

3. docmaker.js check if the context contains `context.versions`. If it does, it runs `generate_versions(context)` method that generates the data to fill template and addes it to config. Also, it takes the `intro.md`, passes it to handlebar and generates a `intro_html.md` (yes, html is stored in md format).

https://github.com/AkMo3/cytoscape.js/blob/e4de815b719aaf594686e6be8bf4aec46f4cd17c/documentation/docmaker.js#L363-L369

4. We change the config to use `intro_html.md` to fill the introduction section.

**Comment by AkMo3** [comment]
Updated Working:

1. Changed the file type of introduction from `md` to `template`
https://github.com/AkMo3/cytoscape.js/blob/d5407717a2100c8bc26df7892cf4e2e382b02ec5/documentation/docmaker.json#L58

2. Changed `compileConfig( config )` to added a new processor for `template`

https://github.com/AkMo3/cytoscape.js/blob/d5407717a2100c8bc26df7892cf4e2e382b02ec5/documentation/docmaker.js#L193-L203

3. If the section type is `template` we call function `templateToHtml(context)`

https://github.com/AkMo3/cytoscape.js/blob/d5407717a2100c8bc26df7892cf4e2e382b02ec5/documentation/docmaker.js#L90-L101

It works in the following way:
 - Sets the configuration/data required by the specific template. In this case, it calls `generate_versions(context)` function.
 - Fetches the `template` (which is a `md` file) in a `html` format. 
 - Supplies this template to Handlebars to compile.
 - Gets the processed final `HTML` by supplying configuration/context.
 - Parses the HTML by marked and returns it.
 
This return HTML is set as section html. 

4. Data Generation is done by the following procedure:
    1. All versions are stored in the file `versions.json`
    2. This file is imported similarly to `docmaker.json`
    3. function generate_versions(context) does the rest of the data processing.
    4. The data structure is identical to below:
  ```json
    {
  "major_release": [
    {
      "version": "3.20",
      "minor_release": [
        {
          "minor_ver": "3.20.3",
          "link": "https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.20.3+is%3Aclosed"
        },
        {
          "minor_ver": "3.20.2",
          "link": "https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.20.2+is%3Aclosed"
        },
        {
          "minor_ver": "3.20.1",
          "link": "https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.20.1+is%3Aclosed"
        },
        {
          "minor_ver": "3.20.0",
          "link": "https://github.com/cytoscape/cytoscape.js/issues?q=milestone%3A3.20.0+is%3Aclosed"
        }
      ]
    }
  ]
}
```

**Comment by AkMo3** [comment]
Add the documentation to `contributing.md` about how to edit documentation.

**Comment by maxkfranz** [comment]
Consider naming re. `template` key, e.g. `template_md` or `mdtemplate`.

Ideally we could avoid underscores.

**Comment by maxkfranz** [comment]
```
{ "name": "Foo", "mdtemplate": "foo", "mdtemplateData": { foo: "bar", baz: 2 } }
```
