### ISSUE TITLE
Create action to support Github Release 

### ISSUE THREAD

**Issue by AkMo3** [AkMo3/cytoscape.js#8]
This task includes the creation of a composite action that :

1. Check for necessary files that should be updated
2. Add the release to git
3. Update the package version and tag the release
4. Push the release changes

**Comment by maxkfranz** [comment]
From the release instructions in the readme:

> 10. Add the the release to git: git add . && git commit -m "Build $VERSION"
> 11. Update the package version and tag the release: npm version $VERSION
> 12. Push the release changes: git push && git push --tags
> 13. Publish the release to npm: npm publish

Notes:

- [x] Re. 12: Permissions need to be set s.t. the GH action can push back to the repo
- [ ] Re. 13: Permissions re. `npm publish` -- implicitly need before 13 `npm login`
  - Currently considering [npm access tokens](https://docs.npmjs.com/about-access-tokens)
  - Let's use a classic token
  - npm in the GH action should be configured to use the token

**Comment by maxkfranz** [comment]
> 13. [Create a release](https://github.com/cytoscape/cytoscape.js/releases/new) for Zenodo from the latest tag. Make sure you wait at least 5 minutes since the last time that you made a release in order for Zenodo to work properly.
> 14. For feature releases: Create a release announcement on the [blog](https://github.com/cytoscape/cytoscape.js-blog). Share the announcement on mailing lists and social media.

- [x] Re. 14: Publishing the [release](https://github.com/AkMo3/cytoscape.js/releases) may be automatable using some GH API
  -  N.b. When these releases are being made, if they happen too close together in time, then Zenodo doesn't work.
  - E.g. patch / bug-fix release:  v1.2.3 (latest/master) and backport v1.1.4 (branch 1.1.x)
  - When a human makes the release: Do 1.1.4 first.  Then wait 5 minutes.  Then do 1.2.3.
  - Closing the milestone => triggers the release => assume then that the person who closes the milestones must wait 5 minutes in between each 'close'
  - Alternative: Leave the releases for Zenodo as separate, manual
  - Evaluate alternatives & pros & cons:
    - Maybe there are simple approaches we could consider  
    - E.g. could we queue the GH actions so only one can run at once?  sleep 300 at the end
    - Generally: we should consider & make a list of pros and cons for all the possibilities that we think of
- [x] Re. 15: Let's create a GH issue in the release pipeline scripts so that for step 14 there is something like this:
  - Title: Create a blog post for release $VERSION
  - Body: Template with instructions for what the maintainer should do, e.g. bullet list
    - 1. Go to this blog repo: link
    - 2. Add a file with this file name pattern in this directory
    - 3. Include these main points in the post: ...
    - ...

**Comment by AkMo3** [comment]
> Re. 14: Publishing the [release](https://github.com/AkMo3/cytoscape.js/releases) may be automatable using some GH API
> 
>     N.b. When these releases are being made, if they happen too close together in time, then Zenodo doesn't work.
>     E.g. patch / bug-fix release: v1.2.3 (latest/master) and backport v1.1.4 (branch 1.1.x)
>     When a human makes the release: Do 1.1.4 first. Then wait 5 minutes. Then do 1.2.3.
>     Closing the milestone => triggers the release => assume then that the person who closes the milestones must wait 5 minutes in between each 'close'
>     Alternative: Leave the releases for Zenodo as separate, manual
>     Evaluate alternatives & pros & cons:
>         Maybe there are simple approaches we could consider
>         E.g. could we queue the GH actions so only one can run at once? sleep 300 at the end
>         Generally: we should consider & make a list of pros and cons for all the possibilities that we think of

We can set a wait timer in our environment for the action to queue up without consuming resources.

![image](https://github.com/AkMo3/cytoscape.js/assets/69365878/899eccf0-83a3-4e6e-9fad-c0a95d349fd1)

**Comment by AkMo3** [comment]
Facing a bug related to `npm version $VERSION` . Need to store logs in the artifacts, and have a look at them.

**Comment by maxkfranz** [comment]
Using a local tool like act might help to make it more debuggable (i.e. perhaps you can access the log file locally): https://github.com/nektos/act

Maybe not.  The best place to start is likely more logging, like we discussed.

**Comment by AkMo3** [comment]
Things to be done:
1. Update documentation for manual and automatic release
2. Do github release
3. Add documentation to wait for 5 min before making next release

**Comment by maxkfranz** [comment]
@AkMo3, the following releases have been made, which you can use to test reproducibility of your release artefacts.

- 3.26.0 (feature release, from unstable branch)
- 3.25.1 (bug fix release, then backport branch master => 3.25.x)
- 3.24.2 (backport release, existing 3.24.x branch)
