### ISSUE TITLE
Run through the release process manually

### ISSUE THREAD

**Issue by maxkfranz** [AkMo3/cytoscape.js#9]
- The release process is outlined in the readme.
- It would be good to run through the process manually and then note any issues or anything that you think of or notice, while you're going through the process.
- Requirements: Change the name of the package in package.json
- Requirement: GH pages permissions?

Outcomes:

- **Identify more details for the other issues (& new issues)**
- Confirm that you have all permissions and setup required for testing (npm demo package etc.)

**Comment by maxkfranz** [comment]
Tested versions:

- 3.25.0 baseline
- 3.26.0 as a new version test
- TODO patch version

**Comment by maxkfranz** [comment]
Akash to run this process manually again (for review, peace of mind) for the patch version flow

**Comment by AkMo3** [comment]
Ran the process for patch release in 3.10.x branch. 

Note: I had rebased the master branch again to cytoscape's master
